// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  // 1. Agrega esto para definir el comando de seed
  migrations: {
    seed: 'ts-node prisma/seed.ts', 
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
